### ISSUE TITLE
There are error parameters in the sample diagram for the project website?

### ISSUE THREAD

**Issue by tp20c5** [NoSweatsTool/NoSweats#2]
On this page, https://www.nosweats.net/Instructions/
![image](https://github.com/NoSweatsTool/NoSweats/assets/71303795/0216c903-240c-4bf8-b674-2642b0625f66)
"600;30;18;20;10;"
I think the first argument 600 will not take effect because it lacks a semicolon.

**Comment by tp20c5** [comment]
In addition, perhaps because English is not my mother tongue, there is a parameter, CPU Load to Idle Transition Threshold , that  I have trouble understanding. It seems to be a sensitivity slider? Use with cooling-off periods, which is what you call CPU Idle Delay. The CLTITT, should be set somewhere in between the CPU idle and CPU working thresholds, however, this is clearly violated in the example above. It seem a bit weird. And I have observed that it is used both when the pattern is up and down, not just TO IDLE?

Anyway, it's a great tool and I think it is even better for everyday use than process lasso if there is no need to set cpu affinity.

**Comment by NoSweatsTool** [comment]
You are right. The example picture does not contain the correct numbers and should have a ; in front of the first value. The  CLTITT is to prevent transitioning to a lower power plan too fast when going under the load threshold. Say your load threshold is 20% and idle is 20%, you wouldn't want it to transition at 19%, but let's say at 15%. I'd have to look at the code but I believe it is only used when transitioning to a lower plan, not higher. 

The next time I edit the website I'll take care of the picture, it was made with a much older version and never updated.
