### ISSUE TITLE
Consider switching the power adjustment plan to the new slider?

### ISSUE THREAD

**Issue by tp20c5** [NoSweatsTool/NoSweats#3]
Suggest. 
In Windows10 and later, the recommended power mode selection is shifting from the classic power plan to the slider that pops up by clicking the battery icon in the taskbar. The power plan is still available, but there are concerns about whether it will be able to operate in the future.
![image](https://github.com/NoSweatsTool/NoSweats/assets/71303795/0bb3c890-a3e3-41ef-9d72-94604d691cbd)

Would you consider using this new approach to functionality?

**Comment by NoSweatsTool** [comment]
Are you asking me to add a slider to nosweats to do the same as what the windows' one does now?

**Comment by tp20c5** [comment]
> Are you asking me to add a slider to nosweats to do the same as what the windows' one does now?

NO, I can see that NoSweats are designed to be user insensitive, so they don't need to be adjusted repeatedly. I just noticed that the set of sliders used by Windows 10 , 
power save mode(only if unplugged) -> longer battery life -> better performance -> optimum performance
, which does not manipulate power plans, so there are occasional conflicts between the two.

**Comment by NoSweatsTool** [comment]
In the plan settings / Power options -> advanced settings, the names haven't changed in the latest Windows 11 build. So for now I am leaving the names as is. 

![image](https://github.com/NoSweatsTool/NoSweats/assets/90943594/3aaeedf1-c26b-4587-b598-e6f59c4de693)

**Comment by tp20c5** [comment]
You're right, I checked my other Windows 11 PC and found that the slider option was the one that was abandoned... So Microsoft has designed a two-tier option that can put a layer of filters on top of the each underlying power plan. And you changed the power plan. That's fine, thx
