### ISSUE TITLE
Consider using performance counters to measure cpu load?

### ISSUE THREAD

**Issue by tp20c5** [NoSweatsTool/NoSweats#4]
I noticed that the cpu load shown by NoSweats is based on cpu usage time rather than more accurate performance counters, whether to consider improvements

**Comment by NoSweatsTool** [comment]
What counters would you suggest? I used cpu usage time as it's a single value easy to monitor, making the tool itself have to to as little as possible calculations.

**Comment by tp20c5** [comment]
> What counters would you suggest? I used cpu usage time as it's a single value easy to monitor, making the tool itself have to to as little as possible calculations.

My suggestion is that for a typical modern device with performance above 4c8t, if the processing time of the program itself is not more than 0.1% on average for 10 seconds, then this performance loss is completely negligible. Thanks to AMD, Intel processors after 10 generations have improved too much... Less performance loss is always good, it's just that the number is now stable at less than 0.01% :）
For reference, I tried it on another taskbar control with the option to switch cpu% fetch, and at least at a 1000ms sample rate I couldn't get a clear indication of how much consumption would increase by using the performance counter.

**Comment by tp20c5** [comment]
So even if NoSweats work fine, I think people couldn't mind consuming a little bit of performance to avoid the confusion of having it vary too much from their dedicated performance monitoring readings, haha

**Comment by NoSweatsTool** [comment]
That makes sense. However, my question remains, what counters would you suggest?

**Comment by tp20c5** [comment]
> That makes sense. However, my question remains, what counters would you suggest?

Performance counters, of course, if the overhead isn't obvious.

**Comment by NoSweatsTool** [comment]
Using the cpu time is simple and accurate enough for for the purpose of NoSweats. I chose to keep NoSweats as simple and lightweight as possible. 

Whether the overhead would be obvious is debatable, NoSweats now has to do hardly anything to determine CPU usage. No complex algorithms with division by zero exceptions which would have to be dealt with etc. Also with the latest (Intel) processors there's models with different types of cores on one CPU so it would be even harder to get an accurate average.

So I'm going to leave it as is for now and am closing this issue.
